### ISSUE TITLE
Route priority

### ISSUE THREAD

**Issue by macalinao** [angular-ui/ui-router#1277]
GitHub has its `/settings` route with a higher priority than the `/:username` route. Is this possible with ui-router? I wasn't able to find any documentation on it. Thanks.

**Comment by orrgal1** [comment]
it doesn't look like exact matches have a higher priority...

**Comment by christopherthielen** [comment]
@orrgal1 I could have been wrong about that, sorry.   I'm not sure if we have specified that behavior

**Comment by orrgal1** [comment]
no worries thanks, just wanted to make sure

**Comment by orrgal1** [comment]
הי,הוספתי אותך עכשיו לשותפים שלי באפליקציית הטרמפים ביפמי. יש שם כבר מלא נהגים וטרמפיסטים וממש קל למצוא טרמפים. האפליקציה תעזור לשנינו לחסוך כסף!אפשר להוריד את האפליקציה פה: www.beepmeapp.comיאללה נתראה בטרמפ :)ביי
    
    


	 

	If you would like to unsubscribe and stop receiving these emails click here.

**Comment by orrgal1** [comment]
Beep
            
                Me
            
        
        הורידו את האפליקציה
        
    
    
        
            

            
                Or Gal
            
        
        
            
                הי angular-ui/ui-router,
            
            
                כדאי לך להצטרף אלינו לביפמי, זאת אפליקצית טרמפים שעוזרת למצוא שותפים לנסיעות יומיות לעבודה/לימודים וגם לנסיעות חד פעמיות. יש כבר המון משתמשים והמון טרמפים. שווה להצטרף, זה יעזור לכולנו לנסוע ביחד ולחסוך הרבה כסף.
            

            
                
                    קבלו את ההזמנה של Or
                
            
            
                
                    צפו בפרופיל של Or בביפמי
                
            
        
    




	 

	If you would like to unsubscribe and stop receiving these emails click here.

**Comment by plong0** [comment]
Found a solution here: http://stackoverflow.com/questions/26389177/angularjs-ui-router-incorrectly-interpreting-url-path-as-paremeter-in-urlroute

Explicitly defining the higher priority route in the $urlRouteProvider works.

ex:
```
$stateProvider.state('foo.bar', {url: '/foo/:bar'});
$stateProvider.state('foo.baz', {url: '/foo/baz'});
$urlRouterProvider.when( '/foo/baz', function($state){ $state.go('foo.baz'); } );
```

**Comment by aeharding** [comment]
I also have this problem. It would be nice if routes declared earlier had priority, or there was some sort of smart detection to see which route is more general.

Is this fixed in ui-router 2?

Just to show what routes were giving me trouble:

```
/contact/new
/contact/:id
```

In this case, `/contact/:id` is always chosen by ui-router. Switching it around gets the desired functionality... But only sometimes. ;)

**Comment by christopherthielen** [comment]
@aeharding what version of ui-router are you on? I think we merged in a PR that tries to prioritize urls based on the number of segments or something

https://github.com/angular-ui/ui-router/commit/b5c57c8ec2e14e17e75104c1424654f126ea4011

**Comment by pietro909** [comment]
Hi, I ran into the same issue and this is what I found so far:
* routes are matched in the order they are registered
* there is no guarantee about the order we are providing, as children states will be queued until parent state is registered
* as of today the only solution 100% working is the one posted by @plong0 http://stackoverflow.com/questions/26389177/angularjs-ui-router-incorrectly-interpreting-url-path-as-paremeter-in-urlroute but it worries me about performances issues.

Is there any news about it?
thanks

**Comment by nateabele** [comment]
We have a naïve sorting implementation that is currently broken in 1.0alpha0 but is being patched in alpha1. We plan to expose an API for managing sort order at some point down the road in 1.0.

**Comment by aeharding** [comment]
@christopherthielen I tried upgrading to that release, but unfortunately, it did not fix the problem. I ended up switching the order of the state declaration, but I still think /contact/new being declared before /contact/:id should ideally catch the route.

Good to head that v1 might fix this. :+1:

**Comment by christopherthielen** [comment]
See #2502

**Comment by rkingon** [comment]
If you're using a numerical `id` vs a string `slug` then you can use regex on the `id` param like so: `url: "/{id:[0-9]+}"`. It will only match numerical id's and allow `new` to route correctly.

**Comment by toxaq** [comment]
Was this resolved at all? I couldn't tell from 2502...  I've just found this issue with nest params on 1.0.3

    /:parent_id/child/new       
    /:parent_id/child/:id

The new route was unreachable.
